#%RAML 1.0 Library
usage: A basic type in the agent client authorisation raml library

types:

  Regime:
    description: The tax regime
    type: string
    enum: [ mtd-sa ]

  Status:
    displayName: Statuses
    enum: [ Pending, Accepted, Rejected, Cancelled ]
    type: string
    description: |
      The status of the current invitation
      Status  | Meaning
      ------- | -------
      ```Pending``` | The invitation has been created, it has not been accepted or rejected by the client. Only the service can set this status
      ```Accepted``` | The client has accepted the invitation. Only the client can set this status
      ```Rejected``` | The client has rejected the invitation. Only the client can set this status
      ```Cancelled``` | The Agency has cancelled the invitation. Only the Agency can set this status
